version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "aravindanr"
      - "jxu-nflx"
      - "apanicker-nflx"
      - "v1r3n"
      - "boney9"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
